export const emails = [
    {
        sender: "GitHub",
        subject: "You have a new follower!",
        message: "Someone just followed your repository. Check it out!",
        date: "June 20",

    },
    {
        sender: "Twitter",
        subject: "New Login from an unknown device",
        message: "We noticed a login from a device we don't recognize. Was this you?",
        date: "June 19",
    },
    {
        sender: "Netflix",
        subject: "New recommendations for you",
        message: "We've added new movies and TV shows we think you'll love. Check them out!",
        date: "June 18",
    },
    {
        sender: "LinkedIn",
        subject: "Job opportunities you might be interested in",
        message: "Here are some job opportunities that match your profile.",
        date: "June 17",
    },
    {
        sender: "Google",
        subject: "Security alert",
        message: "We've detected some unusual activity on your account. Please verify your identity.",
        date: "June 16",
    },
    {
        sender: "Spotify",
        subject: "Your weekly playlist is here!",
        message: "Discover new music with your personalized playlist.",
        date: "June 15",
    },
    {
        sender: "Amazon",
        subject: "Your order has been shipped",
        message: "Your package is on its way! Track it here.",
        date: "June 14",
    },
    {
        sender: "Coursera",
        subject: "New courses you might like",
        message: "Check out these new courses based on your interests.",
        date: "June 13",
    },
    {
        sender: "Dr. Amelia Green",
        subject: "Your appointment reminder",
        message: "This is a reminder for your appointment on June 25th at 3:00 PM.",
        date: "June 12",
    },
    {
        sender: "Fikayo Oyedeji",
        subject: "You are so awesome",
        message: "This is just a small 'thousand word' mail to say how awesome you are.",
        date: "June 11",
    },
    {
        sender: "Philip Ogunmepon",
        subject: "Catch up soon?",
        message: "Hey! It's been a while. Let's catch up over coffee next week.",
        date: "June 10",
    },
    {
        sender: "Alice Wonderland",
        subject: "Mysterious adventure awaits",
        message: "Join me for a tea party in Wonderland. Don't be late!",
        date: "June 9",
    },
    {
        sender: "SpaceX",
        subject: "Mission update",
        message: "Our next mission to Mars is scheduled for launch next month. Stay tuned!",
        date: "June 8",
    },
    {
        sender: "Dumbledore",
        subject: "Important notice",
        message: "Please meet me in my office at your earliest convenience.",
        date: "June 7",
    },
    {
        sender: "Yoda",
        subject: "The Force",
        message: "Strong in you, the Force is. Training you need.",
        date: "June 6",
    },
    {
        sender: "Sherlock Holmes",
        subject: "A new case",
        message: "I have a new case that requires your unique skills. Meet me at 221B Baker Street.",
        date: "June 5",
    },
    {
        sender: "NASA",
        subject: "Astronomy Picture of the Day",
        message: "Check out today's amazing image of the cosmos!",
        date: "June 4",
    },
    {
        sender: "TED Talks",
        subject: "Inspiration for the week",
        message: "Watch these talks to get inspired and motivated for the week ahead.",
        date: "June 3",
    },
    {
        sender: "National Geographic",
        subject: "Explore the world",
        message: "Dive into the latest articles and breathtaking photos from around the globe.",
        date: "June 2",
    },
    {
        sender: "Marie Curie Institute",
        subject: "Research Fellowship Application",
        message: "Your application for the research fellowship has been received.",
        date: "June 1",
    },
    {
        sender: "MasterClass",
        subject: "Learn from the best",
        message: "New classes have been added. Learn from the world's best minds.",
        date: "May 31",
    },
    {
        sender: "Walt Disney Studios",
        subject: "Exclusive Trailer",
        message: "Watch the exclusive trailer for our upcoming blockbuster movie!",
        date: "May 30",
    },
    {
        sender: "Harvard Business",
        subject: "Weekly Insights",
        message: "Get the latest business insights and trends in our weekly newsletter.",
        date: "May 29",
    },
    {
        sender: "Fitbit",
        subject: "Your activity summary",
        message: "Here's your activity summary for the past week. Keep moving!",
        date: "May 28",
    },
];

